# Argus Gate - argus_plc_bridge/config/params.yaml
# Copyright (c) 2026, Luca-G49
# All rights reserved. Licensed under MIT License.

argus_plc_bridge:
  ros__parameters:
    plc_ip: "192.168.1.1"
    remote_port: 45500
    local_port: 57446
    frequency: 50
    
