<?xml version="1.0"?>
<package format="3">
  <name>argus_plc_sim</name>
  <version>0.0.1</version>
  <description>Simulated PLC node for Argus Gate</description>
  <maintainer email="you@example.com">Argus</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>argus_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
